type Props = {
  title?: string;
  children?: React.ReactNode;
};

export default function Head({ title, children }: Props) {
  return (
    <>
      <title>{title ? `${title} | The Movier` : 'The Movier'}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      {children}
    </>
  );
}
